### ISSUE TITLE
Possible Rwstat issues

### ISSUE THREAD

**Issue by halfwit** [droyo/styx#1]
In attempting to use this library, I've come across what may be a bug. 
I am writing some small servers meant to create a specific set of files, and this library has worked great in everything but writes. 
https://github.com/ubqt-systems/ubqtlib/ is the library, https://github.com/ubqt-systems/irc-server is the first implementation, and where I've been having the issues. 
Here's a small log of a session where I mount up and try to run, using the following v9fs incantation - sudo mount -t 9p -o tcp,uname=`whoami`,aname=`whoami`,port=4567 ~/mydir 
https://ptpb.pw/GlHy 
Any insight on what I'm missing (I have tried implementing Gid() returning my clients' name as sent in, as well as Uid() and Muid(), any suggestions on whether this is my side, etc?

**Comment by halfwit** [comment]
Implementing Tsync was the answer, sorry for the issue. Closing.

**Comment by halfwit** [comment]
I'm going to close this for now, while I work on implementing more things that I haven't considered yet.

**Comment by droyo** [comment]
Hi, thank you for trying out my package. The Twstat/Rwstat handling is one of the more complex features of this package, so I'm not surprised that you would find a bug there. My first guess is that one of the "fake" requests generated by the Twstat is not being handled in https://github.com/ubqt-systems/ubqtlib/blob/b12ca9faf1fbf56d995f56e10d0de8e287b541d6/server.go#L74 . Take a look at the Twstat message:

	→ 001 Twstat fid=1 stat="type=ffff dev=ffffffff qid=\"type=255 ver=4294967295 path=ffffffffffffffff\" mode=37777777777 atime=4294967295 mtime=1486086740 length=0 name=\"\" uid=\"\" gid=\"\" muid=\"\""

It looks like you need to handle `styx.Tutimes` and `styx.Tchown` (see [wstat.go](wstat.go#L16-L37)). So the bug may be that I've misunderstood what the "don't touch" value is for the `mode` field of the `Twstat` message. I'll look at a reference implementation.

**Comment by halfwit** [comment]
So, after having implemented all the above, I was bashing my head against various iterations on what else was needed, as writes would either block or outright close the connection. It does seem, to the best of my knowledge that these write issues do not occur with verbose logging turned off. I'll test some more, but I have it working as expected currently as of https://github.com/ubqt-systems/ubqtlib/commit/bd9212b35907c1d0e467e68bfb251dde8954316a

**Comment by droyo** [comment]
I will try and find time on the weekend to run your code and reproduce the issue. Thanks again!

**Comment by halfwit** [comment]
Thanks again @droyo.
