### ISSUE TITLE
Doing a `go get github.com/droyo/styx` results in "use of internal package not allowed" errors

### ISSUE THREAD

**Issue by marzhall** [droyo/styx#18]
Hiyo!

Just tried to grab this package on a new machine using

```
go get github.com/droyo/styx
```

which resulted in the errors:

```
go/src/github.com/droyo/styx/conn.go:10:2: use of internal package not allowed
go/src/github.com/droyo/styx/conn.go:11:2: use of internal package not allowed
go/src/github.com/droyo/styx/request.go:10:2: use of internal package not allowed
go/src/github.com/droyo/styx/conn.go:12:2: use of internal package not allowed
go/src/github.com/droyo/styx/conn.go:13:2: use of internal package not allowed
go/src/github.com/droyo/styx/server.go:8:2: use of internal package not allowed
```
As far as I can tell, it's due to the styx lib trying to import `aqwari.net/net/styx/internal/qidpool` despite being at the path `github.com/droyo/styx`, which golang doesn't appear to approve of based on the "internal package" rules.

The machine is fresh, so it may also be an issue with my `GOPATH` setting or the like.

Is the right fix here to remove those libraries from being "internal"? Thanks!

**Comment by droyo** [comment]
The right fix is to use the import path `aqwari.net/net/styx`
